// Copyright (c) 2011 The LevelDB Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file. See the AUTHORS file for names of contributors.
//
// Decodes the blocks generated by block_builder.cc.
//与block_builder的关联：
//block_builder的finish()返回buffer_
//buffer_作为BlockContents的data_传递给block
//2.24✔

#include "table/block.h"

#include <algorithm>
#include <cstdint>
#include <vector>

#include "leveldb/comparator.h"
#include "table/format.h"
#include "util/coding.h"
#include "util/logging.h"

namespace leveldb {

//初始化Block，保存实际内容、长度、restart array开始的位置
FlatBlock::FlatBlock(const BlockContents& contents)
    : data_(contents.data.data()),
      size_(contents.data.size()),
      owned_(contents.heap_allocated) {
  if (size_ < sizeof(uint32_t)*3) {
    size_ = 0;  // Error marker
    //显然错误，因为restart的数量至少占unit32_t
    //size_的单位是byte
  }else{
    //得到key_size_、value_size_
    const char* ptr = data_ + size_ - 3 * sizeof(uint32_t);
    key_size_ = DecodeFixed32(ptr);
    value_size_ = DecodeFixed32(ptr + sizeof(uint32_t));
    num_cnt_ = DecodeFixed32(ptr + sizeof(uint32_t)*2);
  }
}

FlatBlock::~FlatBlock() {
  if (owned_) {
    delete[] data_;
  }
}


class FlatBlock::Iter : public Iterator {
 private:
  bool is_data_block_;
  const Comparator* const comparator_;
  const char* const data_;       // underlying block contents

  uint32_t current_num_;
  uint32_t num_cnt_;

  Status status_;

  size_t key_size_;//key的固定长度
  size_t value_size_;//value的固定长度

  inline int Compare(const Slice& a, const Slice& b) const {
    return comparator_->Compare(a, b);
  }

  // Return the offset in data_ just past the end of the current entry.
  //返回下一条条目的偏移，（当前value的结尾）
  // inline uint32_t NextEntryOffset() const {
  //   return (value_.data() + value_.size()) - data_;
  // }

 public:
 //data：BlockContents的具体内容，restarts是restart array开始的地方
  Iter(const Comparator* comparator, const char* data, uint32_t num_cnt, const bool is_data_block,
       size_t key_size, size_t value_size)
      : comparator_(comparator),
        data_(data),
        is_data_block_(is_data_block),
        num_cnt_(num_cnt),
        current_num_(0),
        key_size_(key_size),
        value_size_(value_size) {//初始化为最大值的restart编号
  }

  void NextIndex() override {
    Next();
  }
  Slice indexKey() const override {
    assert(IndexValid());
    return key();
  }
  bool IndexValid() const override {
    if(is_data_block_){
      return false;
    }
    return Valid();
  }
  void ResetDataBlock() override {}

  bool IsIndex() override {
    return !is_data_block_;
  }

//如果条目在restart数组之前 说明是有效的
  bool Valid() const override { return current_num_ < num_cnt_ && current_num_ >= 0; }
  Status status() const override { return status_; }
  Slice key() const override {
    assert(Valid());
    return Slice(data_ + current_num_ * (key_size_ + value_size_), key_size_);
  }
  Slice value() const override {
    assert(Valid());
    return Slice(data_ + current_num_ * (key_size_ + value_size_) + key_size_, value_size_);
  }

//迭代器向前移一个条目  后->前
  void Next() override {
    assert(Valid());
    current_num_++;
  }

//向后移一个条目  后->前
  void Prev() override {
    assert(Valid());
    current_num_--;
  }

  void Seek(const Slice& target) override { 
    //std::cout<<"FlatBlock::Iter::Seek target:"<<target.ToString()<<std::endl;
    Slice key;

    key = Slice(target.data(), target.size()-8);


    uint32_t left_bound = DecodeFixed32(target.data() + target.size()-8);
    uint32_t right_bound = DecodeFixed32(target.data() + target.size()-4);   

    right_bound > num_cnt_-1 ? right_bound = num_cnt_-1 : right_bound = right_bound;

    if(right_bound < left_bound){
      left_bound = 0;
      right_bound = num_cnt_-1;
    }
    
    //std::cout<<"seek target key:"<<key.ToString()<<" left_bound:"<<left_bound<<" right_bound:"<<right_bound<<std::endl;

    // uint32_t left = left_bound;
    // uint32_t right = right_bound;   // 半开区间 [left, right)

    uint32_t left = left_bound;
    uint32_t right = right_bound + 1;   // 注意：右边界改成「开区间」

    // for(int i = left; i <= right+1; i++){
    //   Slice cur_key(data_ + i * (key_size_ + value_size_), key_size_);
    //   std::cout<<"  current key:"<<cur_key.ToString()<<std::endl;
    // }

    while (left < right) {
      uint32_t mid = left + ((right - left) >> 1);
      const char* entry_ptr = data_ + mid * (key_size_ + value_size_);
      Slice mid_key(entry_ptr, key_size_);

      // 找第一个 >= key
      if (Compare(mid_key, key) < 0) {
        left = mid + 1;
      } else {
        right = mid;
      }
    }

    current_num_ = left;

    //std::cout << "after seek current_num_: " << current_num_ << std::endl;
  }

//定位到第一个条目
  void SeekToFirst() override {
    current_num_ = 0;
    //std::cout<<"FlatBlock::Iter::SeekToFirst"<<" key:"<<key().ToString()<<std::endl;
  }

//定位到最后一个条目
  void SeekToLast() override {
    current_num_ = num_cnt_ - 1;
  }

 private:
  void CorruptionError() {
    status_ = Status::Corruption("bad entry in block");
  }

  // bool ParseNextKey() {
  //   current_num_ ++;
  //   return true;
  // }
};

//在块上新建一个迭代器(属于Block类的方法)
Iterator* FlatBlock::NewIterator(const Comparator* comparator, const bool is_data_block) {
  if (size_ < sizeof(uint32_t)) {
    return NewErrorIterator(Status::Corruption("bad block contents"));
  }

  return new Iter(comparator, data_, num_cnt_, is_data_block, key_size_, value_size_);
}

}  // namespace leveldb
